version: '3.6'

services: 
  # Backend 
  smart-brain-api:
    container_name: backend
    build: ./
    volumes:
      - ./:/usr/src/smart-brain-api
    command: npm start
    working_dir: /usr/src/smart-brain-api
    ports:
      - "3000:3000"
    environment:
      POSTGRES_URI: postgres://matt:matt@postgres:5432/smart-brain-docker
      REDIS_URI: redis://redis:6379
    
  # PostgresSQL
  postgres:
    container_name: postgres
    build: ./postgres
    environment:
      POSTGRES_USER: matt
      POSTGRES_PASSWORD: matt
      POSTGRES_DB: smart-brain-docker
      POSTGRES_HOST: postgres
    ports:
      - "5431:5432"

  # Redis
  redis:
    container_name: redis
    image: redis
    ports:
      - "6379:6379"